### ISSUE TITLE
Replacement of current API Logging facilities

### ISSUE THREAD

**Issue by jwestberg** [Findwise/Hydra#108]
StageGroups (#106) will somewhat break logging support when something is run as a group, as stages will log on the group level rather than on the stage level.

I think it could be easily replaced by a logging webservice alongside the other services in Core.

**Comment by jwestberg** [comment]
It turns out that the current logging facilities are also not thread safe. If you log too much in a thread group, they will deadlock.

So. Uh. This needs to be fixed pretty soon.

**Comment by remen** [comment]
One idea would be to use logback and http://logback.qos.ch/manual/appenders.html#SocketAppender

**Comment by laserval** [comment]
Closed in #197
