### ISSUE TITLE
Ability to add documents in JSON

### ISSUE THREAD

**Issue by jwestberg** [Findwise/Hydra#109]
Would be great to provide an interface for inserting documents via the Admin Service! Would be helpful when integrating Hydra to non-java systems.

**Comment by laserval** [comment]
I have started work on this, used in https://github.com/laserval/hydra-one-click, here: https://github.com/laserval/Hydra/commits/new-doc-endpoint

**Comment by jwestberg** [comment]
Cherrypick that commit into a separate branch and merge o-hoy!
