### ISSUE TITLE
Make MemoryConnector fully compliant

### ISSUE THREAD

**Issue by jwestberg** [Findwise/Hydra#111]
Quite a few interfaces in MemoryConnector, particularly with PipelineReader and PipelineWriter are left blank and unimplemented.

Implementing these would be a good step on the way to doing in-memory federation:

Hydra-Core (mongodb) with one stage: Memory-Core, where Memory-Core acts a Hydra Core as normal, but caches all documents to the stages.

**Comment by laserval** [comment]
Am I right in that #136 will resolve this issue?

**Comment by jwestberg** [comment]
No. Wemanaged to implement the "in memory federation" I discuss, but we did it without resolving the underlying issue this discusses: MemoryConnector still cannot store or read Pipelines :(

**Comment by laserval** [comment]
I see.
I'm not sure how this should be implemented. If the memorydb is ever supposed to be an alternative to mongodb, it needs to be available to external processes somehow so it can be configured by e.g. the admin service.

**Comment by laserval** [comment]
Oops, misclicked!

**Comment by laserval** [comment]
What would the purpose be of implementing PipelineReader/Writer? Could such functionality be used by anything currently?

**Comment by jwestberg** [comment]
Not really. But, it would be good for integration testing if mocking isn't an option. I see this as a low priority issue.

**Comment by laserval** [comment]
I agree, it could be nice to have.
