### ISSUE TITLE
Refactor integration out of non-integration tests!

### ISSUE THREAD

**Issue by jwestberg** [Findwise/Hydra#112]
A lot of tests right now require MongoDB even though they shouldn't. We could easily mock MongoDB in a lot of cases instead. 

Some other tests are also good candidates for having most of the code replaced by mocks as they end up testing previously already tested integration.

**Comment by rgraneru** [comment]
Yes, this is very true. Is good to have some integration tests, but the
shouldn't be run as unit tests, at each compile.

**Comment by rgraneru** [comment]
should i close the other issue?

**Comment by Nycander** [comment]
I started looking into this in #202, most of the mongodb code would require refactoring to support good unit testing.

Should the integration tests be moved to the verify-stage of the maven build and perhaps exist in another folder or have a naming convention of some kind?

**Comment by remen** [comment]
I suggest using maven-failsafe-plugin and naming all integration tests
*IT.java

http://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html
