### ISSUE TITLE
Remove integration tests from unit tests

### ISSUE THREAD

**Issue by rgraneru** [Findwise/Hydra#117]
At the moment some of the hydra modules are running unit-tests that rely on mongodb in order to be asserted, and this breaks the build if mongodb is not running. These should be set up as integration tests that is run at will and not as unit tests that are run on every compile.

This goes for core, database and mongodb

**Comment by rgraneru** [comment]
I suggest that we rename the files that contain the integration tests from RemotePipelineTest to RemotePipelineIT (integrationtest) and then use the maven failsafe plugin to do the integration tests at will. 

These can be run with mvn verify

**Comment by jwestberg** [comment]
Is this not the same as #112?

**Comment by jwestberg** [comment]
Closing this as a duplicate.
