### ISSUE TITLE
Core: Multiple Stages per JVM

### ISSUE THREAD

**Issue by jwestberg** [Findwise/Hydra#12]
One Library of stages can easly be used to run several different stages in different threads, instead of requiring separate processes for each. 

This could easily be implemented by having a Main-class in the libraries tasked with maintaining Stage instances. Since AbstractStage handles parameterization of stages on it's own via the REST interfaces, one can easily start several stages at once. All this new Main class would need to know is a list of stageNames to start from that particular library.

**Comment by laserval** [comment]
Is this not resolved by pull request #106?

**Comment by jwestberg** [comment]
Yes.
