### ISSUE TITLE
Tika stage fails to extract content

### ISSUE THREAD

**Issue by remen** [Findwise/Hydra#120]
Hey everyone,

I struggled last week to get TikaStage to work correctly. The problem was that Tika managed to find the correct content-type for the data, but could not extract contents. Even weirder was that I couldn't replicate the problem when running the same code from within Netbeans.

In the end, I have managed to isolate the problem to some sort of resource conflict when using "jar-with-dependencies". To fix the problem, I've instead used the onejar plugin: https://code.google.com/p/onejar-maven-plugin/

Shall I upload the change to the pom.xml? Has anyone else had the same problem?

**Comment by laserval** [comment]
Does it work with Maven 3? The site seems to suggest it is built only for Maven 2 and it would be unfortunate to depend on older versions of Maven.

**Comment by remen** [comment]
You're right! It works for Maven 3, but fails for Maven 2. We should probably enforce Maven 3 in the pom.xml somehow, but that is a separate problem.

Thanks! Closing.

**Comment by remen** [comment]
I completely misunderstood your comment @laserval, you asked whether the onejar-maven-plugin was compatible with Maven 3 whereas I understood it as asking whether the Tika Stage built successfully with maven 3!

So, I thought for a while that it worked when building with Maven 3, but it seems I have triggered the bug again. So, reopening and will get back to you on whether onejar works for maven 3.

**Comment by laserval** [comment]
This is odd, haven't heard anyone else having problems with the dependency-plugin like this. Could you see if anyone else has the same problem? Perhaps have them build the jar-with-dependencies and then put it in the pipeline.

**Comment by remen** [comment]
I'll perform a more thorough investigation during the day and try to find out if and why the with-dependencies strategy is failing randomly on my builds. I'll get back to you.

**Comment by remen** [comment]
Ok, I found the problem. Both vorbis-java-tika.jar and tika-parsers.jar contain META-INF/services/org.apache.tika.parser.Parser which list available parser implementations. When merging the jar files, we need to merge these files. The assembly plugin does not support this, but the shade plugin does. I'll send a pull request where I've changed the pom for tika-stages to use the shade plugin instead. Do you think we could merge this into upstream asap?

Below is the diff between the significant file built with mvn2, mvn3 and shade respectively. As you can see, mvn2 used the file from vorbis-java-tika whereas mvn3 used the file from tika-parsers. Using the shade plugin, both file contents are merged (hurra!)

``` diff
--- mvn2/META-INF/services/org.apache.tika.parser.Parser    2012-11-23 12:03:45.000000000 +0100
+++ mvn3/META-INF/services/org.apache.tika.parser.Parser    2012-03-07 12:47:48.000000000 +0100
@@ -1,3 +1,47 @@
-org.gagravarr.tika.FlacParser
-org.gagravarr.tika.OggParser
-org.gagravarr.tika.VorbisParser
+#  Licensed to the Apache Software Foundation (ASF) under one or more
+#  contributor license agreements.  See the NOTICE file distributed with
+ ... [etc]
+#  See the License for the specific language governing permissions and
+#  limitations under the License.
+
+org.apache.tika.parser.asm.ClassParser
+org.apache.tika.parser.audio.AudioParser
+ ... [etc]
+org.apache.tika.parser.xml.DcXMLParser
+org.apache.tika.parser.xml.FictionBookParser
+org.apache.tika.parser.chm.ChmParser
```

``` diff
--- mvn3/META-INF/services/org.apache.tika.parser.Parser    2012-03-07 12:47:48.000000000 +0100
+++ shade/META-INF/services/org.apache.tika.parser.Parser   2012-11-23 13:02:06.000000000 +0100
@@ -45,3 +45,6 @@
 org.apache.tika.parser.xml.DcXMLParser
 org.apache.tika.parser.xml.FictionBookParser
 org.apache.tika.parser.chm.ChmParser
+org.gagravarr.tika.FlacParser
+org.gagravarr.tika.OggParser
+org.gagravarr.tika.VorbisParser
```

**Comment by remen** [comment]
If this works, I would suggest using the shade plugin instead of jar-with-dependencies everywhere for consistency.

**Comment by laserval** [comment]
To me it seems to be an issue with the vorbis-tika plugin and how that is linked into tika-parsers. So the issue will appear with Ogg, Vorbis and Flac, when using Maven3, and for everything else on Maven2.

From http://stackoverflow.com/questions/1607220/how-can-i-merge-resource-files-in-a-maven-assembly it seems to be possible to merge the files in the Assembly plugin as well, but it looks cumbersome.

The vorbis-tika package seems to have some POM problems (see https://issues.apache.org/jira/browse/TIKA-967, https://github.com/Gagravarr/VorbisJava/issues/2) but they are probably unrelated.

**Comment by Gagravarr** [comment]
Apache Tika itself had the same problem with merging the services file for the Tika-App CLI. The fix was in r1355741 in case that helps you too - http://mail-archives.apache.org/mod_mbox/tika-commits/201206.mbox/%3C20120630141502.6886C23888CD@eris.apache.org%3E

**Comment by remen** [comment]
Ahh... cool, thanks! Same solution too, which is comforting.
