### ISSUE TITLE
Stage groups endpoint in Admin service

### ISSUE THREAD

**Issue by laserval** [Findwise/Hydra#129]
It should be possible to GET the currently configured Stage Groups, as well as POST stages to groups.

Currently, the stages/{stage-name} POST endpoint puts the stage in its own group.
Stage groups can be listed on the root endpoint.

**Comment by jensbengtsson** [comment]
Should there be two different end points, one where you don't need a group name (aka the current one) and one where you provide a group name?

So like this

@RequestMapping(method = RequestMethod.POST, value = "/libraries/{id}/stages/{groupName}/{stageName}")

**Comment by laserval** [comment]
Closed by #138
