### ISSUE TITLE
Hydra Test Setups (inserter) is dependant on hydra-basic-stages

### ISSUE THREAD

**Issue by rgraneru** [Findwise/Hydra#174]
If you try to compile examples after building root (api, database and core)  the compiling fails because of the dependency to hydra-basic-stages. The reason Examples depend on hydra-basic-stages is because of the StraightPipelineSetup. This is a very old way of adding jars to the database and configuring stages. I suggest that we remove the example, or at least add the jars from local path and not from resources.

**Comment by laserval** [comment]
I resolved the dependency problem with #175, but there's still lots of archaic code in `examples`.

**Comment by laserval** [comment]
I'm closing this as the inserter is now a separate project (see #280 ) and the dependency is gone as well.
