### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by remen** [Findwise/Hydra#180]
I am guessing that this is due to that we are trying to open a port which the server does not allow:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.findwise.hydra.net.HttpRESTHandlerTest
10:24:37.691 [I/O dispatcher 1] INFO  c.f.hydra.net.HttpResponseWriter - Got ID ping!
10:24:37.743 [Thread-2] ERROR com.findwise.hydra.net.RESTServer - I/O error in RESTServer: Failure binding socket to address 0.0.0.0/0.0.0.0:20000

...

Results :
Failed tests:   testAccessRestrictions(com.findwise.hydra.net.HttpRESTHandlerTest): Server should have been working, we are connecting through localhost...
Tests run: 41, Failures: 1, Errors: 0, Skipped: 0

```

**Comment by jwestberg** [comment]
Pretty sure there is something slightly more complicated afoot. There are other tests that rely on port binding, since the start method will attempt repeatedly to find an open port to use. 

I think it might be something along the lines of the Travis VM not resolving localhost to the calling IP.

**Comment by remen** [comment]
Yeah, you're right. I've downloaded the travis image (vagrant ftw!) and
will debug locally. I think it is due to 127.0.0.1 resolving to
localhost.localdomain because of /etc/hosts. Will check.

Anyway, while looking at the code I have two points I would like to raise:

1) I think the logic for knownHosts is "wrong". We take the client
ip-address and do a reverse lookup to get the hostname and check if it's in
the list. I don't think this is a good idea, since a) an IP-address can be
associated with several hostnames and b) this will become strange if we add
an ip-address to the list. I think a better solution is to resolve the
hosts in the knownHosts list (i.e. not do reverse lookup), but will have to
do more testing to see whether it works as intended.

2) Why do we even have this logic? If we are going to do IP-based security,
wouldn't a firewall be better suited?

/Petter

**Comment by remen** [comment]
Damn it, couldn't replicate with the vagrant image. Maybe have the wrong
version... Still digging.

**Comment by jwestberg** [comment]
Petter, I think you're right on both accounts. Preferably, one might have the option of doing either option, and hostnames are probably the least important one, since it's so error-prone.

As for why the feature exists, well of course, it would be better to use a firewall. This is implemented in Hydra too though in order to support use cases where you want to be able to debug a pipeline remotely from an IDE without having to call a network administrator to allow access from the development machine, if you're in that kind of environment.

**Comment by remen** [comment]
One of my recent pull requests improves (imho) the resolving. Check it out
and merge if satisfactory.

ok, i can understand the second point. But as you know, more features means
more maintenance and makes it harder to change.

**Comment by jwestberg** [comment]
Yes, I agree. It was added for a very specific use case and there was no proper review-process at the time to decide on the fate of the feature. It could definitely be a candidate feature for removal in a future major version. 

Looking at the pull request as we speak.

**Comment by remen** [comment]
Seems to work now. Closing.
