### ISSUE TITLE
AbstractStage.init() should throw more generic exception.

### ISSUE THREAD

**Issue by ebbesson** [Findwise/Hydra#189]
It is possible that one might want to refuse a stage to start other than missing required arguments, such as validating that an integrating system is unavailable or that authentication is invalid.

**Comment by laserval** [comment]
My proposal for this is to add a second checked exception, `InitException` or something similar, to the `init()`method. That way we can still differentiate failure to provide needed stage parameters/arguments from stage initialization problems (such as connection failure).
