### ISSUE TITLE
Update stages to correctly mark their required Parameters

### ISSUE THREAD

**Issue by laserval** [Findwise/Hydra#190]
Many stages have `@Parameters` that are checked for existence manually by the stage `init()` method, instead of using the `required` keyword in the annotation.

**Comment by rgraneru** [comment]
I have done this sometimes, but will stop it. I've also failed to use the
required keyword correctly.

But when I run unit tests, can i check for required parameters?
Den 27. mars 2013 11:02 skrev "Olof Nilsson" notifications@github.com
følgende:

**Comment by laserval** [comment]
Yeah, I think it's mostly remnants from before the annotations had parameters, or at least before those were used. If you happen across any odd things in a stage, go ahead and update it. It's really annoying to have to look in the logs to notice if a stage requires some parameters or not.

Not sure about the unit tests, it's possible it's handled when the main method is called in `AbstractStage`.

**Comment by jwestberg** [comment]
To run unit tests, I would suggest simply calling the `setParameters(Map<String, Object>)` method as specified in AbstractStage on the constructed stage object. That is the method called to performs all parameter injections.

Do note though, that required is NOT actually enforced by AbstractStage at this point. That is something that would probably make life easier for developers in the future, and would probably be a worthwhile feature to implement.

**Comment by laserval** [comment]
Started working on this, adding a check for the `required` value on the `@Parameter` annotation and throwing `RequiredArgumentException` in `setParameters()`. Will try out switching some stages over to relying on it as well. Branch : https://github.com/laserval/Hydra/tree/abstractstage-required-argument-check

**Comment by laserval** [comment]
Fixed in #206
