### ISSUE TITLE
AbstractStage should verify required stage parameters

### ISSUE THREAD

**Issue by jwestberg** [Findwise/Hydra#191]
AbstractStage should assume the responsibility of ensuring that `@Parameters` marked _required_ are actually set and initialized at startup of a stage.

Right now, this type checking is left up to the stage `init()` method, leading to the required flag not really being useful for anything other than documentation. And documentation is boring.

**Comment by rgraneru** [comment]
Ok. Then I will use the init method for required checking for now. But I
will use the required annotation correctly as well for future use
Den 28. mars 2013 13:21 skrev "Joel Westberg" notifications@github.com
følgende:

**Comment by laserval** [comment]
Closed in #206
