### ISSUE TITLE
Race condition when adding documents with file attachments

### ISSUE THREAD

**Issue by remen** [Findwise/Hydra#198]
When adding a document with binary file attachments, there is a time-period in which the document exists in the mongo database, but the files haven't been committed yet. This leads to stages sometimes being unable to fetch the binary attachment, giving rise to log messages such as:

```
2013-04-12 11:29:21 : ERROR  : Thread-17 : ChalmersPreProcessStage : Node gave an unexpected response: HTTP/1.1 404 Not Found
2013-04-12 11:29:21 : ERROR  : Thread-17 : ChalmersPreProcessStage : Message: No file found by the name data for this document
```

**Comment by rgraneru** [comment]
Is this on Unix or Windows or both?
Den 12. apr. 2013 12:20 skrev "Petter Remen" notifications@github.com
følgende:

**Comment by remen** [comment]
Platform should not matter.

**Comment by rgraneru** [comment]
Does should a wish or a fact? :-)  As it is now, Windows mongodb misbehaves
more than the Unix one
Den 12. apr. 2013 19:01 skrev "Petter Remen" notifications@github.com
følgende:

> Platform should not matter.
>

**Comment by remen** [comment]
Hehe. Confirmed problem on both mac and linux at least. The reason for the
bug is quite simple actually, the document has to be committed to mongodb
before the binary attachments since the attachments uses the ID generated
by mongo. However, the stages happily pick up the document but fails when
trying to reference the attachments. Anyway, I have a solution strategy in
mind. Hope to send pull request next week.
