### ISSUE TITLE
Adding the possibility to say how long a running stage should live before it would self destruct

### ISSUE THREAD

**Issue by rgraneru** [Findwise/Hydra#201]
I'm having some issues with giant xml fields that are regexped quite extensively, and this sometimes takes a lot of time, and sometimes the running stage process goes on forever, keeping other, better documents a possibility to get through the pipeline. When this happens I just have to kill the offending stage and it will restart and the rest goes smoothly. 

So what I was thinking was to add the possibility to add in the stage configuration a way to autokill a running stage after a certain amount of time.

**Comment by jwestberg** [comment]
Could probably be implemented as a timeout per document in AbstractStage? 

Unrelated, but, I have to ask, why are you parsing XML with a regular expression?

**Comment by rgraneru** [comment]
Because a little idiocy now and then never hurts. :-)

But I agree. We use xslt for the other xml data gathering. And I will
exchange the regexp with xslt soon.
Den 18. apr. 2013 13:51 skrev "Joel Westberg" notifications@github.com
følgende:

**Comment by laserval** [comment]
Resolved by #264. Closing.
