### ISSUE TITLE
Various exceptions trying to use SolrOutputStage with 0.3.0

### ISSUE THREAD

**Issue by svetob** [Findwise/Hydra#203]
I'm trying to set up a pipeline using Hydra 0.3.0 that ends with the SolrOutputStage stage. The other stages have worked fine but I have ran into some exceptions trying to get this stage to work.

First when building Hydra 0.3.0 from source, I get this error when the stage launches: 

> ...
> 2013-05-15 13:37:43 : INFO   : Thread-11 : com.findwise.hydra.StageRunner : Launching with command java -cp /var/lib/hydra/stress/solr-out-stage/\* -jar /var/lib/hydra/stress/solr-out-stage/hydra-solr-out-stage.jar solr-out-stage localhost 12001 false 12002
> 2013-05-15 13:37:43 : INFO   : Thread-10 : com.findwise.hydra.StageRunner : Starting stage group tokenizer-stage. Times started so far: 0
> ...
> **2013-05-15 13:37:45 : INFO   : Thread-26 : com.findwise.hydra.StreamLogger : Received message from stage solr-out-stage (stderr): Exception in thread "main" java.lang.ExceptionInInitializerError
> 2013-05-15 13:37:45 : INFO   : Thread-26 : com.findwise.hydra.StreamLogger : Received message from stage solr-out-stage (stderr):     at com.findwise.hydra.stage.AbstractStage.main(AbstractStage.java:270)
> 2013-05-15 13:37:45 : INFO   : Thread-26 : com.findwise.hydra.StreamLogger : Received message from stage solr-out-stage (stderr): Caused by: java.lang.ClassCastException: org.slf4j.impl.SimpleLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
> 2013-05-15 13:37:45 : INFO   : Thread-26 : com.findwise.hydra.StreamLogger : Received message from stage solr-out-stage (stderr):     at com.findwise.hydra.Logging.<clinit>(Logging.java:22)
> 2013-05-15 13:37:45 : INFO   : Thread-26 : com.findwise.hydra.StreamLogger : Received message from stage solr-out-stage (stderr):     ... 1 more**
> 2013-05-15 13:37:45 : ERROR  : Thread-11 : com.findwise.hydra.StageRunner : Stage group solr-out-stage terminated unexpectedly with exit value 1
> 2013-05-15 13:37:45 : ERROR  : Thread-11 : com.findwise.hydra.StageRunner : The stage group solr-out-stage did not start. It will not be restarted until configuration changes.

This is my configuration file:

{
        "stageClass" : "com.findwise.hydra.output.solr.SolrOutputStage",
        "solrDeployPath" : "http://localhost:8080/solr/main",
        "fieldMappings" : {
                "name" : "name",
                "text" : "text",
                "language" : "language",
                "sentences" : "sentences",
                "persons" : "persons",
                "orgs" : "organizations",
                "locs" : "locations"
        },
        "sendALL" : false,
        "commitWithin" : 1000,
        "query" : { "touched" : {"ner-tagger-stage" : true } }
}

To see if I could solve this issue, I created a copy of the solrOutputStage maven project in which I removed all log dependencies and log calls. The stage now launches fine. But when it processes a document it fails with a InvalidClassException:

> 2013-05-15 12:57:15 : DEBUG  : I/O dispatcher 1 : com.findwise.hydra.net.HttpResponseWriter : Printing document with ID {"_time":1368622548,"_machine":244033565,"_inc":325440925,"_new":false} to stage solr-out-stage
> 2013-05-15 12:57:15 : DEBUG  : solr-out-stage : com.findwise.hydra.stage.AbstractProcessStage : Got new doc {"_inc":325440925,"_new":false,"_time":1368622548,"_machine":244033565} to process.
> 2013-05-15 12:57:15 : DEBUG  : solr-out-stage : com.findwise.hydra.stage.AbstractOutputStage : Processing document: {"_inc":325440925,"_new":false,"_time":1368622548,"_machine":244033565}
> **2013-05-15 12:57:15 : INFO   : Thread-91 : ch.qos.logback.classic.net.SocketNode : Caught java.io.IOException: java.io.InvalidClassException: ch.qos.logback.classic.spi.ThrowableProxyVO; local class incompatible: stream classdesc serialVersionUID = -773438177285807139, local class serialVersionUID = 685387990886325422**
> 2013-05-15 12:57:15 : INFO   : Thread-91 : ch.qos.logback.classic.net.SocketNode : Closing connection.
> 2013-05-15 12:57:15 : DEBUG  : Thread-91 : ch.qos.logback.classic.net.SimpleSocketServer : Removing ch.qos.logback.classic.net.SocketNode/127.0.0.1:34827
> 2013-05-15 12:57:15 : DEBUG  : I/O dispatcher 2 : com.findwise.hydra.net.RESTServer : Connection closed: 0.0.0.0:12001<->127.0.0.1:42394[CLOSED]
> 2013-05-15 12:57:15 : DEBUG  : I/O dispatcher 1 : com.findwise.hydra.net.RESTServer : Connection closed: 0.0.0.0:12001<->127.0.0.1:42395[CLOSED]
> 2013-05-15 12:57:15 : ERROR  : Thread-11 : com.findwise.hydra.StageRunner : Stage group solr-out-stage terminated unexpectedly with exit value 1

..after which the stage restarts and promptly fails in the same way when processing a document again.

At this point I am unsure how to proceed?

**Comment by remen** [comment]
I think this is due to SolrOutputStage containing a conflicting slf4j backend. Have not investigated further.

**Comment by laserval** [comment]
Looks like you could be right, @remen. After a look at the dependencies, it seems we introduced `slf4j 1.7.2` when replacing the logging functionality. Solrj uses `1.6.4` and we also use `slf4j-simple 1.6.4` in the stage. I'll have a look at cleaning up the slf4j dependencies, it seems Core is using a different version as well.

**Comment by laserval** [comment]
I believe I've fixed this issue in #205, but haven't tested Solr out especially - I got the same issue with another stage and fixing the dependencies resolved it. When we get this merged to master we can pick the commit onto 0.3.x so it will get in a 0.3.1 release soonish.

**Comment by svetob** [comment]
Nice response time, thanks! :) Will try this out again in a day or two.
