### ISSUE TITLE
SolrOut requires FieldMappings to be set

### ISSUE THREAD

**Issue by ebbesson** [Findwise/Hydra#220]
It is not in the 0.3.1 build, but has appeared in current snapshot (0.4.0) Not if it should be there

**Comment by jwestberg** [comment]
```
@Parameter(required = true, description = "A map specifying which fields in the Hydra document becomes which fields in Solr. The value of an entry must be one of either String or List<String>.")
private Map<String, Object> fieldMappings = new HashMap<String, Object>();
@Parameter(required = true, description = "If set, fieldMappings will be ignored and all fields will be sent to Solr.")
private boolean sendAll = false;
```

We have clearly messed this up. 

Temporary fix for the problem without changing code would be to simply provide an empty value for `fieldMappings` if you're using `sendAll`

**Comment by laserval** [comment]
Yep, it looks ok in the solr-3.6 output stage, so I must have gone a bit crazy with the required params there ;)
