### ISSUE TITLE
CmdLineInserter as a separate project

### ISSUE THREAD

**Issue by laserval** [Findwise/Hydra#222]
The `CmdLineInserter` class that is the main class of the runnable jar build by the `examples` project, should be a separate project. Perhaps a `tools` project?

**Comment by rgraneru** [comment]
Yes. It should. I've startet to look at it in order to get it to support
stage groups, but haven't finished yet. Maybe I should pull it out of the
examples project while I do that?

**Comment by laserval** [comment]
Yeah, do that.

**Comment by laserval** [comment]
I've done most of this in this branch: https://github.com/laserval/Hydra/tree/inserter-project

Perhaps there are more tools that could be extracted.
