### ISSUE TITLE
Tika stages tests should run offline

### ISSUE THREAD

**Issue by laserval** [Findwise/Hydra#235]
The tests in hydra-tika-stages require an internet connection to work.

They should not.

**Comment by ssimon** [comment]
+1
Removing the tests would requiring internet access would be better than the current solution, but it shouln't be very hard to mock that part?

**Comment by remen** [comment]
I like wiremock for mocking http.

/Petter

**Comment by remen** [comment]
Apologies for the multiple references from commits. It seems rebasing and pushing doesn't remove the "dangling" old commits from github. And neither the references nor the commits can be removed (other than deleting the remen/Hydra repository).

Anyway, pull request #237 is my proposed fix for this issue.
