### ISSUE TITLE
Add database port number to configuration

### ISSUE THREAD

**Issue by laserval** [Findwise/Hydra#251]
Currently the default port is used for the database, and no configuration option is visible for changing the port.

**Comment by ssimon** [comment]
But you are allowed to use localhost:123 as host right..?

**Comment by laserval** [comment]
Ah right, got confused by the MongoDB driver API. Although I'd prefer an explicit option.

**Comment by Nycander** [comment]
I tried to fix this in PR #254 :)

**Comment by laserval** [comment]
After experimenting with this, and with replica sets in MongoDB, I'm not sure this is needed. I think it would be better to do things as in #256

**Comment by Nycander** [comment]
Agreed!

**Comment by laserval** [comment]
Closing, aiming to implement with MongoClientURI instead.
