### ISSUE TITLE
Complication errors for database/src/main/java/com/findwise/hydra/DatabaseException.java. Class overrides explicit Java7 constructor

### ISSUE THREAD

**Issue by ebbesson** [Findwise/Hydra#259]
Constructor :
Exception(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) does not exist in Java 6 and this causes a compliation error when trying to complie Hydra with Java 6

See
Java 6 :http://docs.oracle.com/javase/6/docs/api/java/lang/Exception.html
Java 7: http://docs.oracle.com/javase/7/docs/api/java/lang/Exception.html

**Comment by laserval** [comment]
Good catch.

**Comment by laserval** [comment]
Added java 6 build to the Travis CI conf on master.
