### ISSUE TITLE
Travis build failed on testProcess_execution_timeout_fails_document

### ISSUE THREAD

**Issue by remen** [Findwise/Hydra#279]
It seems there is something wrong with the execution timeouts or their tests. However, seems to be semi-random:

https://travis-ci.org/Findwise/Hydra/jobs/14497071#L9035

**Comment by laserval** [comment]
Yes, in some cases the stage that is used for the test manages to fetch another document after `stopStage()` has been called. The tests expect the stages to process an exact number of documents, but sometimes it has time to process a second one (concurrency...). The test stages run until they've reached some limit of documents they expect to process, then signal a shutdown using `stopStage()`, which ensures the stage will shut down eventually - once it's done processing.

We could add some tolerance to the tests so stages can process one additional document, but this does show that there is some uncertainty for stages that want to shut down - they might process another document even if they are trying to shut down.

I'm not sure what we can do to fix the problem though...

**Comment by laserval** [comment]
Just to further note that the tests are randomly failing: the @Findwise build server (using Jenkins) has not had any failures.

It's clearly concurrency and timing issues due to the low performance of Travis that makes these bugs show themselves. Probably a good thing! :)

**Comment by remen** [comment]
From your description, I would say that the bug is in the _test_. I don't think it is necessary to guarantee that sending a `stopStage()` message will have such high precision.

Maybe there is some way of getting the "andemening" (swedish) of the tests without actually counting the number of documents being processed? I'll have a look at it right away. Failing tests (even/especially random ones) should be considered blockers for any further development. I'd rather remove the functionality altogether than have a failing test.

**Comment by remen** [comment]
I'm sorry, since I reviewed and merged the code myself I should have been able to understand it better; but I don't.

I've had a look at that specific test and it looks wrong to me:

``` java
@Test
public void testProcess_execution_timeout_fails_document() throws Exception {
    stage = new InterruptibleWaitingStage();
        ...
    map.put("processingTimeout", 1);
        ...
    stage.start();

    while (stage.isAlive()) {
        Thread.sleep(10);
    }
    verify(ld, times(1)).addError(eq(stage.getStageName()), any(Throwable.class));
}
```

But InterruptibleWaitingStage is interruptible, so in fact, the thread should always be alive. The fact that it is failing to stay alive shows that we don't really understand `task.cancel(interrupt = true)`.

I don't want to continue digging at the moment, since it's taking too much time and I'm not getting paid for it right now :)

**Comment by remen** [comment]
While trying to come up with a test strategy that would work, I got _really_ scared by the complexity of the current solution. I'll start the discussion here, but we might have to have a realtime chat. I think the current implementation is very hard to understand, and therefore hard to maintain.

Look at `AbstractProcessStage.run()`

``` java
@Override
public void run() {

    setContinueRunning(true);

    while (isContinueRunning()) {
        try {
            LocalDocument doc = fetch();
            if (doc == null) {
                Thread.sleep(holdInterval);
            } else {
                performProcessing(doc);
            }
        } catch (Exception e) {
            logger.error("Caught exception while running", e);
            killStage();
        }
    }
    shutdownProcessing();
}
```

What _is_ and what _should be_ the difference between killStage and shutdownProcessing? Why `isContinueRunning()` instead of `Thread.interrupted()`?

Going down the rabbit whole of `killStage`and `shutdownProcessing` led to a bunch of shutdown hooks and other stuff that scare me (StageGroups), and I have no idea how it's supposed to work.

**Comment by laserval** [comment]
I agree that this is too complex and that much of the implementation is hidden in abstract classes. A quick response:
- `killStage()` is intended for when a clean shutdown is no longer possible. The [default implementation](https://github.com/Findwise/Hydra/blob/master/api/src/main/java/com/findwise/hydra/stage/JvmStageKiller.java) (as set [here](https://github.com/Findwise/Hydra/blob/master/api/src/main/java/com/findwise/hydra/stage/AbstractStage.java#L45)) does a `System.exit()`. The `shutdownProcessing()` method should be the clean shut down method.
- The test methods in `AbstractProcessStageTest` rely on stages that shut themselves down after a certain number of processed documents. I'm afraid I named the stages badly, since I never really got a good test of interruptibility in there... The stages should stop being alive after a while though, since they call their own `stopStage()` method.

But yeah, I don't really like this either. I think the big problem is the nested abstract classes. The stage class handles both running an entire process and handling the processing of documents.

**Comment by remen** [comment]
Yeah, agreed. #285 helps a little bit since it moves the responsibility of creating the Stage instances out from AbstractStage itself.

Anyway, back to the issue at hand. I still don't quite understand the behaviour of the test and how it works together with `InterruptibleStage`. Let's have a look:

In `AbstractProcessStage` we have the following logic:

``` java
try {
    future.get(timeout);
} except (TimeoutException e) {
    boolean cancelSucceeded = future.cancel(sendInterrupt = true);
    if (!cancelSucceeded) {
        throw e;
    }
}
```

But that indicates to me that if future.cancel returns true, then the stage will keep alive and process more documents.

Now, look at `InterruptibleWaitingStage`:

``` java
public void process(LocalDocument doc) throws ProcessException {
    try {
        while (true) {
            sleep(100);
        }
    } catch (InterruptedException e) {
        return;
    } finally {
        stopStage();
    }
}
```

If the sleep is interrupted, then process() will return without error. I would have thunk that that would make future.cancel think that it succeeded. Now finally, look at the test again:

``` java
if(!stage.isAlive) {
    sleep(100);
}
```

Why would the stage ever die? As I said, I think it's strange that the test is _not_ hanging indefinitely, and I think the reason is that we don't understand `future.cancel`.

**Comment by remen** [comment]
Nevermind, I suddenly saw the

``` java
} finally {
    stopStage();
}
```

Maybe there is some way of making this clearer? Could we instead simply have:

``` java
try {
    while (true) {
        sleep(100);
    }
} catch (InterruptedException e) {
    stopStage();
}
```

**Comment by remen** [comment]
Now I'm starting to understand. Both `stopStage` and `isContinueRunning` is synchronized, so they cannot interleave. So `isContinueRunning` must be called before `stopStage`. But that would mean that future.cancel was called and returned true before `stopStage` was called. But how can that be? Well, looking at the source for FutureTask.cancel and it doesn't in any way _wait_ for the task to end before returning. It just sets a "isCanceled" flag and sends an interrupt. The return code is set to false if and only if the task either has already been cancelled or has already run to completion.

Ok, but that would mean that our logic for checking the cancel exit status is wrong. We should be able to create a stage that _doesn't_ quit when sent interrupts, and it should result in a hanging stage.

Agreed?

**Comment by laserval** [comment]
> Ok, but that would mean that our logic for checking the cancel exit status is wrong. We should be able to create a stage that doesn't quit when sent interrupts, and it should result in a hanging stage.
> 
> Agreed?

Agreed!

**Comment by remen** [comment]
Hmm... rebasing really screws up github, which is understandable. The last commit is the proper one.
