### ISSUE TITLE
What's up with releaseDocument and keepLock in RemotePipeline?

### ISSUE THREAD

**Issue by remen** [Findwise/Hydra#289]
Hey,

While refactoring, I noticed that the methods releaseDocument and keepLock were only ever being called in the unit tests, and not actually by the framework itself. Below is a branch of master in which I've deleted the methods entirely, and all the tests pass. What is the reason for them?

https://github.com/remen/Hydra/compare/keeplock

**Comment by jwestberg** [comment]
They're fossils from a removed feature of the framework dealing with allowing the fetching of a document multiple times by the same stage, as well as the ability for an OutputStage to be able to mark a document as "Pending" meaning it was essentially done with it, but had yet to actually output it.

In short, they are relics of poor design, and an apparently incomplete removal of those poorly designed features :)

**Comment by remen** [comment]
Thanks Joel! I'll make a pull request then.
