### ISSUE TITLE
StageGroup JVMs fail to start when path to working directory contains spaces

### ISSUE THREAD

**Issue by laserval** [Findwise/Hydra#314]
When a stagegroup JVM is started by the Hydra Core, its classpath is constructed by concatenating the absolute paths of all the stage JARs that the group should run. Since the JARs are fetched by Core and put in its working directory, the classpath will contain the path to the working directory. If there is a space anywhere in the path, the main class (`GroupStarter`) can't be found and the stage JVM exits.

This means that Hydra cannot run with spaces in the path, at least not on *nix systems.

Currently this looks like this:

```
09:06:25.436 [Thread-6] INFO  com.findwise.hydra.NodeMaster - Pipeline has been updated
09:06:25.491 [Thread-10] INFO  com.findwise.hydra.StageRunner - Starting stage group setstatic. Times started so far: 0
09:06:25.494 [Thread-10] INFO  com.findwise.hydra.StageRunner - Launching with command java -cp "/Users/olof.nilsson/Code/Dump/Hydra with spaces/pipeline/setstatic/hydra-basic-stages-jar-with-dependencies.jar" com.findwise.hydra.stage.GroupStarter setstatic localhost 12001 false 12002
09:06:25.600 [Thread-13] INFO  com.findwise.hydra.StreamLogger - Received message from stage setstatic (stderr): Error: Could not find or load main class com.findwise.hydra.stage.GroupStarter
09:06:25.614 [Thread-10] ERROR com.findwise.hydra.StageRunner - Stage group setstatic terminated unexpectedly with exit value 1
09:06:25.614 [Thread-10] ERROR com.findwise.hydra.StageRunner - The stage group setstatic did not start. It will not be restarted until configuration changes.
```

**Comment by ssimon** [comment]
Should we start by adding a note to the setup readme, until we fixed the
issue?

**Comment by laserval** [comment]
I've been trying to fix this, by updating the commons-exec dependency to a newer version, manually quoting the classpath, escape spaces in the classpath and so on. I've not been successful, and can't seem to find any reason for why spaces should be a problem. I haven't seen if this is true for windows, so might be a *nix issue entirely.

**Comment by laserval** [comment]
@remen suggested dropping the quoting and just supplying a plain classpath string, which seems to work well on *nix systems. I'm having problems on windows though, looking into it.
