### ISSUE TITLE
oldDocuments is not capped if created by solrOutput after sending a document to solr

### ISSUE THREAD

**Issue by rgraneru** [Findwise/Hydra#96]
When letting hydra-core or the inserter create the mongo database (pipeline) the oldDocuments collection is created as a capped collection. If you then manually drop this collection and then run solrOutput, it will re-create the oldDocuments collection, but this time not capped. 

This creates a problem for software that runs callbacks to the mongodb and uses a cursor that demands that the oldDocuments database is capped.

**Comment by jwestberg** [comment]
I don't think this is a bug. Don't drop the oldDocuments collection, as it represents the internal state of Hydra, and will be created as capped as part of the initiation process on the database.

I don't think it should be a requirement that the framework has to recover gracefully from that kind of tampering - if anything, perhaps it should crash instead? I'm not sure what the performance hit would be in doing this, but I'm not entirely convinced it would be worth it.

**Comment by rgraneru** [comment]
I might agree that it is not a bug, but it would be nice if you got a
warning of some sort. Especially since you can tamper with most of the
other collections, and they will re-create themselves as needed. Its very
good for debugging. It might be enough to print a debug warning as you
create the capped collection in the first place, and then the next hacker
won't be so bold and delete it, as I did :)

**Comment by jwestberg** [comment]
I think it would make more sense to provide a less hurtful way of debugging... :)

**Comment by rgraneru** [comment]
Hopefully stuff will get better when the admin api is fully funtional and we got a pretty gui on top.
